### PR TITLE
Updates for DTS audio formats

### PR DESCRIPTION
**Pull request by pmaness**
updated DTS and DTS-HD references
updated sample entry and object type descriptions for all DTS code points
added reference DTS-UHD
added sample entry code point dtsy
added ObjectType codes for dtsx and dtsy using codes 0xB2 and 0xB3
added brands dts1 dts2 dts3

### CODE REVIEW

**Comment by dwsinger** [comment]
We're re-defining the meaning of some existing code-points here and it's not obvious that the effect is the same and that (e.g.) conformant files remain conformant, but I think we'll have to trust that the registration request has considered this.

**Comment by pmaness** [comment]
I don't think it was intended. One of the CSVs was giving me fits, can't recall which one now. It would look good in the table, then do something unexpected when rendering the HTML.
I'll give it a look when I'm back on the ground. Traveling back from Japan today.

-phil



This message is sent from my phone, subject to fat fingers and auto-correct.


-------- Original message --------

**Comment by dwsinger** [comment]
There were GH reported conflicts, I hope I resolved correctly

**Comment by dwsinger** [comment]
I’ll deal with them, don’t worry


> On Feb 9, 2018, at 10:13 , Phillip Maness <notifications@github.com> wrote:
> 
> I don't think it was intended. One of the CSVs was giving me fits, can't recall which one now. It would look good in the table, then do something unexpected when rendering the HTML.
> I'll give it a look when I'm back on the ground. Traveling back from Japan today.
> 
> -phil
> 
> 
> 
> This message is sent from my phone, subject to fat fingers and auto-correct.
> 
> 
> -------- Original message --------
> From: David Singer <notifications@github.com>
> Date: 2/9/18 10:05 AM (GMT+09:00)
> To: mp4ra/mp4ra <mp4ra@noreply.github.com>
> Cc: Phillip Maness <Phillip.Maness@xperi.com>, State change <state_change@noreply.github.com>
> Subject: Re: [mp4ra/mp4ra] Updates for DTS audio formats (#8)
> 
> 
> @dwsinger approved this pull request.
> 
> OK, but there are extra spaces in the specs table after the second comma for DTS and DTS-HD
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mp4ra_mp4ra_pull_8-23pullrequestreview-2D95288802&d=DwMCaQ&c=oHEeDb9RL7QTKhcPWM8xGA&r=teHhisd8q1IRlEzu4k-woiW_21iYDcg1mRMu92pCQBw&m=T04WX6Kv2WOMT3ZfGq8RUO3reWXmAmFh46bnH9tWrCw&s=1cq_-GWxFH_Yt7MrHlJwGghSj4B53sMtz0MdWxOCmuk&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGWNuw4-5FOjkrUSeKiSueuZ8Yh-5FRA1WI7ks5tS5nagaJpZM4R0ite&d=DwMCaQ&c=oHEeDb9RL7QTKhcPWM8xGA&r=teHhisd8q1IRlEzu4k-woiW_21iYDcg1mRMu92pCQBw&m=T04WX6Kv2WOMT3ZfGq8RUO3reWXmAmFh46bnH9tWrCw&s=an_GGu6M8RAzi42VsmVeyXDXUsE2qzsuM0ZbXfPcs9U&e=>.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Pull request merged**
